name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Grant the token the permissions the Pages actions need
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build (optional)
        run: |
          echo "No build step required for this repository"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./src

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
